namespace :coverage do
  desc 'Collates all result sets generated by the different test runners'
  task :report, %w[pattern] do |_task, args|
    require 'simplecov'

    SimpleCov.collate Dir[args.pattern]
  end
end
