openapi: 3.0.0

info:
  title: Post API
  version: 0.0.0

paths:
  /posts/{id}:
    get:
      summary: "Post API"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              title:
                type: "string"
                example: "title"
              body:
                type: "string"
                example: "body"
