name: Deploy GitHub Pages

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        run: |
          gh release download ${{ github.event.inputs.release_tag }}
          tar xzf github_pages_artifact.tgz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github_pages_artifact

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
